name: Simulasi CI/CD Express

on:
  push:
    branches:
      - main

jobs:
  build-deploy-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm install

      - name: Build step (simulasi)
        run: echo "Build selesai."

      - name: Jalankan server di background & test pakai curl
        run: |
          nohup npm start &
          sleep 5
          curl http://localhost:3000
