name: CI/CD Simulasi (Express)

on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm install

      - name: Simulasi Build/Testing
        run: echo "Build sukses"

      - name: Jalankan server di background & test curl
        run: |
          node server.js &
          sleep 3
          curl http://localhost:3000
