name: CI/CD Simulasi Static Website

on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout kode
        uses: actions/checkout@v3

      - name: Simulasi Build (contoh)
        run: |
          echo "Build dimulai..."
          mkdir build
          cp index.html build/
          echo "Build selesai dan disimpan ke folder build/"

      - name: Simulasi Deploy
        run: |
          echo "Simulasi deploy ke folder lokal 'deploy'"
          mkdir -p deploy
          cp build/index.html deploy/
          echo "Deploy selesai ke folder deploy/"

      - name: Simulasi Tes (curl ke localhost)
        run: |
          echo "Karena ini file static, gak bisa curl ke localhost"
          echo "Simulasi test selesai."
